
spring.jpa.show-sql=true

spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true
spring.datasource.driverClassName=org.h2.Driver
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.datasource.url=jdbc:h2:file:./data/att

spring.datasource.username=password
spring.datasource.password=password
management.endpoints.web.exposure.include=health
management.endpoint.shutdown.enabled= true
spring.web.error.include-message=always
att.security.jwt.secret=${ATTENDANCE_ACCOUNTING_JWT_SECRET}
spring.h2.console.settings.web-allow-others=false
att.integration.attendance-accounting.base-url=${ATTENDANCE_ACCOUNTING_BASE_URL:http://localhost:8081}
spring.config.import=optional:classpath:async-messages.yml

spring.jpa.properties.hibernate.temp.use_jblc_metadata_defaults=false
# Enable Web and Security Debug Logging
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet=TRACE
# Force Spring Boot to log full stack traces for errors
spring.web.error.include-exception=true
spring.web.error.include-stacktrace=always