
-- create table hours
CREATE TABLE att_work_sessions
(
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    tenant_id          INTEGER                                              NOT NULL,
    user_id            INTEGER,
    updated_by         VARCHAR(255),
    sys_update_date    TIMESTAMP(6) WITH TIME ZONE,
    status             VARCHAR(10),
    work_date          DATE,
    open_session_date  TIMESTAMP(6) WITH TIME ZONE,
    close_session_date TIMESTAMP(6) WITH TIME ZONE,
                       PRIMARY KEY (id)
);

-- =================. face 2 (not now):================
-- partitions: work_date(gange,monthly)
-- index: tenant_id ,user_id,work_date
-- index:tenant_id,work_date