
-- create table hours
CREATE TABLE att_work_sessions
(
    id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    tenant_id          INTEGER                                              NOT NULL,
    user_id            INTEGER,
    updated_by         VARCHAR(255),
    sys_update_date    TIMESTAMP(6) WITH TIME ZONE,
    status             VARCHAR(10),
    work_date          DATE,
    open_session_date  TIMESTAMP(6) WITH TIME ZONE,
    close_session_date TIMESTAMP(6) WITH TIME ZONE,
                       PRIMARY KEY (id)
);

-- =================. face 2 (not now):================
-- partitions: work_date(range,monthly)
-- index: tenant_id ,user_id,work_date
-- index:tenant_id,work_date

CREATE TABLE att_month_statistic
(
    tenant_id        INTEGER NOT NULL,
    user_id          INTEGER NOT NULL,
    month_start_date DATE    NOT NULL,
    work_days        INTEGER NOT NULL,
    overtime_hours   INTEGER NOT NULL,
    total_work_hours INTEGER NOT NULL,
    vacation_days    INTEGER NOT NULL,
    sick_days        INTEGER NOT NULL,
    updated_by       VARCHAR(255),
    sys_update_date  TIMESTAMP(6) WITH TIME ZONE,

    CONSTRAINT pk_att_month_statistic
        PRIMARY KEY (tenant_id, user_id, month_start_date)
);

CREATE TABLE att_user_leave_days
(
    tenant_id       INTEGER                                              NOT NULL,
    user_id         INTEGER                                              NOT NULL,
    leave_date      DATE        NOT NULL,
    leave_type      VARCHAR(10) NOT NULL, -- 'VACATION' | 'SICK'
    amount DOUBLE NOT NULL,               -- 1.0 = full day, 0.5 = half day
    updated_by      VARCHAR(255),
    sys_update_date TIMESTAMP(6) WITH TIME ZONE,

    CONSTRAINT pk_att_user_leave_days PRIMARY KEY (tenant_id, user_id, leave_date, leave_type)
);

CREATE INDEX idx_att_user_leave_days_tenant_date
    ON att_user_leave_days (tenant_id, leave_date);